// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Deadline    pgtype.Date
	IsCompleted pgtype.Bool
}
